name: Deploy to DigitalOcean Kubernetes

on:
  push:
    branches:
      - main  # Trigger the workflow when pushing to the `main` branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up kubectl (Kubernetes command line tool)
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          kubectl-version: 'latest'

      # Configure kubectl to use the DO K8s cluster
      - name: Configure kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          kubectl config set-context --current --namespace=default

      # Debugging step to check the services and their external IP
      - name: Get Kubernetes services
        run: |
          kubectl get svc

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Cache Docker layers to speed up builds
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image to DockerHub
      - name: Build and push Docker image
        run: |
          docker build -t narayananraj/app:latest .
          docker push narayananraj/app:latest

      # Deploy the application to Kubernetes using kubectl
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml  # Adjust the path to your Kubernetes deployment YAML
          kubectl apply -f k8s/service.yaml     # Adjust the path to your Kubernetes service YAML

      # Wait for the LoadBalancer to get an external IP (optional step for waiting)
      - name: Wait for LoadBalancer IP
        run: |
          kubectl wait --for=condition=ready svc/your-app-service --timeout=600s
          kubectl get svc your-app-service
